#Use Fahrenheit, otherwise use Celcius.
useFahrenheit = true
#Show degree symbol next to temperature value.
showDegreeSymbol = true
#Position of debug info, one of: [TOPLEFT, TOPCENTER, TOPRIGHT, BOTTOMLEFT, BOTTOMCENTER, BOTTOMRIGHT]
position = "TOPRIGHT"
#Debug text X offset
#Range: -100 ~ 100
debugOffsetX = 3
#Debug text Y offset
#Range: -100 ~ 100
debugOffsetY = 3
#The size of the text info (multiplier)
#Range: 0.5 ~ 2.0
scale = 0.5
#Temperature color range (Format (cold->hot): #3ab3da->#f9801d)
temperatureColorRange = "#3ab3da->#f9801d"
#Position of the CENTER_GLOBE HUD if enabled, one of: [TOPLEFT, TOPCENTER, TOPRIGHT, BOTTOMLEFT, BOTTOMCENTER, BOTTOMRIGHT]
globePosition = "BOTTOMCENTER"
#CENTER_GLOBE HUD X offset
#Range: -500 ~ 500
globeOffsetX = 0
#CENTER_GLOBE HUD Y offset
#Range: -500 ~ 500
globeOffsetY = 50
#CENTER_GLOBE HUD Y offset
#Range: -500 ~ 500
globeTextOffsetY = 90
#Set to true to force position of the water bar.
forceWaterBarPosition = false
#Position of the Water Bar HUD if forceWaterBarPosition is true, one of: [TOPLEFT, TOPCENTER, TOPRIGHT, BOTTOMLEFT, BOTTOMCENTER, BOTTOMRIGHT]
waterBarPosition = "BOTTOMCENTER"
#Water Bar HUD X offset
#Range: -500 ~ 500
waterBarOffsetX = 96
#Water Bar HUD Y offset
#Range: -500 ~ 500
waterBarOffsetY = 50
